title = "Not Just a Statistic"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-massively"
googleanalytics = "UA-124600408-1"
disqusShortname = "hugo-massively"

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
# [params.posts]
#     foldername = "post"
#     pagesize = "6"
#     featuredpost = "true"
