# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://notjustastatistic.netlify.com/"

# Title of your site
title = "Not Just a Statistic"

# Your copyright notice - appears in site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy; NotJustAStatistic 2018"

theme = "minimal-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#preserveTaxonomyNames = true
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-124600408-1"

# Get last modified date for content from Git?
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/readfiles/bfconfig/
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[params]
  # Your details.
  name = "Not Just a Statistic"
  bio = "A blog on Data Science and how it impacts your daily life."

  avatar = "portrait.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.

  location = "Los Angeles, CA"

  # Discussion link (e.g. link to a forum, mailing list, or chat).
  #   Uncomment line below to use.
  #   discussion = { name = "Discuss", url = "https://discourse.gohugo.io" }

  # Date and time format (refer to Go's date format: http://fuckinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Jan 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "3:04 PM"

  # Display comment count? Requires commenting to be enabled.
  comment_count = true

  # Enable native social sharing buttons?
  sharing = true

  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = false

#  [[params.social]]
#    icon = "instagram"
#    icon_pack = "fa"
#    link = "//instagram.com/jhu247"
#    text = "Instagram"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "https://www.linkedin.com/in/christopher-maerzluft-28902b61/"
    text = "LinkedIn"

#  [[params.social]]
#    icon = "twitter"
#    icon_pack = "fa"
#    link = "//twitter.com/jhu247"
#<img src="/static/img/hero.jpg" alt="" width="100%"/><img src="/static/img/portrait.jpg" alt="" width="100%"/>    text = "Twitter"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "https://github.com/cmaerzluft"
    text = "Github"

# Taxonomies.
# [taxonomies]
#   tag = "tags"
#   category = "categories"
#   publication_type = "publication_types"
