---
title: Welcome
author: Christopher Maerzluft
date: '2019-10-05'
slug: welcome
categories: []
tags: ["Hello"]
header:
  caption: ''
  image: ''
---

## The Idea.

Welcome to my first blog entry! I was going to do a quick introduction followed by an equally quick mini-analysis but then I started doing said analysis and it kept getting bigger and bigger as I thought of more things to add and explore... instead I am just writing this introduction and doing the fun stuff elsewhere. So, the quick rundown is this: I hope to use this blog to share my passion for data science and share with others the way I approach data science.

At a high level, data science is really a field comprised of two disciplines - statistics and computer science. Unfortunately, these two fields don't teach each other very well very often. This is somewhat understandable as both fields are rather large, but as data science grows more distinguished from its parents the average practionsher will need a more balanced approach to data science. At the moment, statisticians have the biggest ground to make up because computer scientists have designed algorithms that process such vast amounts of data they are able to arrive at near-human to super-human predictions without any need to understand the relationships within the data. Statisticians meanwhile make reasonably good models that are easy to interpret and quick to calculate. At the end of the day, most people are more interested in an accurate prediction than something they can understand and thus computer scientists have the advantage. Still, I suspect that the statisticians will be crucial to the ongoing development of data science as a field.

As for me, I hope to be someone that practices data science from both angles. I wish to develop sound statistical models that are taken advantage of using in well designed algorithms and code using the best technology for the job. I will use this blog to explore random topics that I find interesting: from poker to the stock market, and from developing AI that can beat simple games to predicting sporting event outcomes. As I explore these topics I will lay out how I research them and how I begin to build models; I will also describe how the code I write works and why I wrote it the way I did. I can't always promise to be the best coder or the best modeler though. In truth, this blog is really about giving me a systematic way to learn new methods and practices and I commit to continually learning and sharing what I learn with you the reader.

Well, that's it for now. I hope you enjoy everything that comes next.

Best,
Chris

