---
title: Poker! I Barely Know her!
author: Christopher Maerzluft
date: '2018-09-11'
slug: simple-poker
categories: []
tags: []
header:
  caption: ''
  image: ''
---

## If I Were a Betting Man...

I recently listened to a story on the podcast for [Moth Radio Hour](https://themoth.org/stories/the-big-things-you-dont-do). The speaker, [Annie Duke](https://en.wikipedia.org/wiki/Annie_Duke), described how she came to be in a high stakes game of Texas Hold'em with nine of the other world's best poker players. As a part of her story she mentioned that she first started playing poker when her [brother](https://en.wikipedia.org/wiki/Howard_Lederer), one of the other nine players at the high stakes game, on a small cocktail napkin gave her a small list of hands which she could play when she first started. He said, "stick to these hands and you will be fine". As with most stories I hear, I wanted to know more.  
  
Now if you aren't familiar with the Texas Hold'em you can find a nice summary of the game and its rules [here](http://www.wsop.com/poker-games/texas-holdem/). In that link you will even find a list of probabilities for being dealt certain grouping of pocket cards. What that list is missing though is the true value of the hands.  
  
The holy grail of Texas Hold'em is the royal flush. This hand comes from making a suited straight starting with a ten and finishing with an ace. The list of probabilities in the above link show that the probability of getting two cards that are suited and connected and help create royal flush (e.g. 10/Jack, Jack/Queen, etc.) is 1%. The probability of completing the royal flush is even higher: 0.000154%. In other words, if you are waiting for this hand, you are in the wrong game. So if this hand is so rare, which hands are more common but still worth playing which hands actually result in wins. If you were a world class poker player which hands would you rely on the most, which ones would you put on a small cocktail napkin?

## The Deal

The answer to the question above can have many answers. For this analysis we are going to keep it simple. We are simply going to ask, which starting hole cards end up winning the most games in the long run. In order to do this, we will simulate a hand of poker with eight players. We will track what card each player has and who ends up winning if no player folds their hands. After this we will play another hand, and another, and another; we will do this thousands of times or more until we feel confident that we have found the hands most likely to result in wins.

```{r}
# Libraries Needed
library(knitr)
# Load Data
load("~/Desktop/Miscellaneous/Data Blog/TexasHoldEm/Data/simulated_100k_games.Rdata")
print(summary(games))
```